package domain

import (
	"sort"
	"strings"
)

// ModelDefinition represents metadata about a model.
type ModelDefinition struct {
	ID              string                 `json:"id"`              // e.g. "claude-sonnet-4.5"
	Name            string                 `json:"name"`            // Display name
	Provider        string                 `json:"provider"`        // "kiro", "openai", etc.
	ContextWindow   int                    `json:"contextWindow"`   // Max tokens
	MaxOutputTokens int                    `json:"maxOutputTokens"` // Max output
	InputPrice      float64                `json:"inputPrice"`      // Per 1M tokens
	OutputPrice     float64                `json:"outputPrice"`     // Per 1M tokens
	Capabilities    []string               `json:"capabilities"`    // ["vision", "tools", "streaming"]
	IsActive        bool                   `json:"isActive"`        // Available for use
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
}

// ModelRegistry holds all available model definitions.
type ModelRegistry struct {
	Models map[string]*ModelDefinition `json:"models"` // key: "provider/model-id"
}

// DefaultModelRegistry returns a registry with common models.
func DefaultModelRegistry() *ModelRegistry {
	return &ModelRegistry{
		Models: map[string]*ModelDefinition{
			// Kiro models
			"kiro/claude-sonnet-5": {
				ID:              "claude-sonnet-5",
				Name:            "Claude Sonnet 5",
				Provider:        "kiro",
				ContextWindow:   1000000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     10.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"kiro/claude-opus-5": {
				ID:              "claude-opus-5",
				Name:            "Claude Opus 5",
				Provider:        "kiro",
				ContextWindow:   1000000,
				MaxOutputTokens: 128000,
				InputPrice:      5.0,
				OutputPrice:     25.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"kiro/gpt-5.6-terra": {
				ID:              "gpt-5.6-terra",
				Name:            "GPT-5.6 Terra",
				Provider:        "kiro",
				ContextWindow:   272000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     12.0,
				Capabilities:    []string{"vision", "tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"kiro/glm-5": {
				ID:              "glm-5",
				Name:            "GLM-5",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 16384,
				InputPrice:      1.0,
				OutputPrice:     3.2,
				Capabilities:    []string{"tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"kiro/claude-sonnet-4.5": {
				ID:              "claude-sonnet-4.5",
				Name:            "Claude Sonnet 4.5",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      3.0,
				OutputPrice:     15.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"kiro/claude-haiku-4.5": {
				ID:              "claude-haiku-4.5",
				Name:            "Claude Haiku 4.5",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      0.8,
				OutputPrice:     4.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"kiro/deepseek-3.2": {
				ID:              "deepseek-3.2",
				Name:            "DeepSeek 3.2",
				Provider:        "kiro",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      0.14,
				OutputPrice:     0.28,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"kiro/qwen3-coder-next": {
				ID:              "qwen3-coder-next",
				Name:            "Qwen3 Coder Next",
				Provider:        "kiro",
				ContextWindow:   32000,
				MaxOutputTokens: 8192,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"kiro/claude-opus-4.6": {
				ID:              "claude-opus-4.6",
				Name:            "Claude Opus 4.6",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      15.0,
				OutputPrice:     75.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"kiro/claude-opus-4.5": {
				ID:              "claude-opus-4.5",
				Name:            "Claude Opus 4.5",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      15.0,
				OutputPrice:     75.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"kiro/claude-sonnet-4.6": {
				ID:              "claude-sonnet-4.6",
				Name:            "Claude Sonnet 4.6",
				Provider:        "kiro",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      3.0,
				OutputPrice:     15.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"kiro/deepseek-3.1": {
				ID:              "deepseek-3.1",
				Name:            "DeepSeek 3.1",
				Provider:        "kiro",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      0.14,
				OutputPrice:     0.28,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			// OpenAI models
			"openai/gpt-5.6-sol": {
				ID:              "gpt-5.6-sol",
				Name:            "GPT-5.6 Sol",
				Provider:        "openai",
				ContextWindow:   1050000,
				MaxOutputTokens: 128000,
				InputPrice:      5.0,
				OutputPrice:     30.0,
				Capabilities:    []string{"reasoning", "vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-5.6-terra": {
				ID:              "gpt-5.6-terra",
				Name:            "GPT-5.6 Terra",
				Provider:        "openai",
				ContextWindow:   1050000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     12.0,
				Capabilities:    []string{"reasoning", "vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-5.6-luna": {
				ID:              "gpt-5.6-luna",
				Name:            "GPT-5.6 Luna",
				Provider:        "openai",
				ContextWindow:   1050000,
				MaxOutputTokens: 128000,
				InputPrice:      0.2,
				OutputPrice:     1.2,
				Capabilities:    []string{"reasoning", "vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-5.4": {
				ID:              "gpt-5.4",
				Name:            "GPT-5.4",
				Provider:        "openai",
				ContextWindow:   400000,
				MaxOutputTokens: 128000,
				InputPrice:      1.25,
				OutputPrice:     10.0,
				Capabilities:    []string{"reasoning", "vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-5.4-mini": {
				ID:              "gpt-5.4-mini",
				Name:            "GPT-5.4 Mini",
				Provider:        "openai",
				ContextWindow:   400000,
				MaxOutputTokens: 128000,
				InputPrice:      0.25,
				OutputPrice:     2.0,
				Capabilities:    []string{"reasoning", "vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-4.1": {
				ID:              "gpt-4.1",
				Name:            "GPT-4.1",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      2.5,
				OutputPrice:     10.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-4.1-mini": {
				ID:              "gpt-4.1-mini",
				Name:            "GPT-4.1 Mini",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-4.1-nano": {
				ID:              "gpt-4.1-nano",
				Name:            "GPT-4.1 Nano",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.04,
				OutputPrice:     0.16,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-4o": {
				ID:              "gpt-4o",
				Name:            "GPT-4o",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      2.5,
				OutputPrice:     10.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/gpt-4o-mini": {
				ID:              "gpt-4o-mini",
				Name:            "GPT-4o Mini",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/o3": {
				ID:              "o3",
				Name:            "o3",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 100000,
				InputPrice:      10.0,
				OutputPrice:     40.0,
				Capabilities:    []string{"reasoning", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/o3-mini": {
				ID:              "o3-mini",
				Name:            "o3-mini",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 65536,
				InputPrice:      1.1,
				OutputPrice:     4.4,
				Capabilities:    []string{"reasoning", "tools", "streaming"},
				IsActive:        true,
			},
			"openai/o4-mini": {
				ID:              "o4-mini",
				Name:            "o4-mini",
				Provider:        "openai",
				ContextWindow:   128000,
				MaxOutputTokens: 65536,
				InputPrice:      1.1,
				OutputPrice:     4.4,
				Capabilities:    []string{"reasoning", "tools", "streaming"},
				IsActive:        true,
			},
			// GLM (Zhipu AI / Z.ai) models
			"glm/glm-5.2": {
				ID:              "glm-5.2",
				Name:            "GLM 5.2",
				Provider:        "glm",
				ContextWindow:   1000000,
				MaxOutputTokens: 16384,
				InputPrice:      1.4,
				OutputPrice:     4.4,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"glm/glm-5.1": {
				ID:              "glm-5.1",
				Name:            "GLM 5.1",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      1.4,
				OutputPrice:     4.4,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"glm/glm-5": {
				ID:              "glm-5",
				Name:            "GLM 5",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      1.4,
				OutputPrice:     4.4,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"glm/glm-4.7": {
				ID:              "glm-4.7",
				Name:            "GLM 4.7",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      1.0,
				OutputPrice:     3.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"glm/glm-4.6": {
				ID:              "glm-4.6",
				Name:            "GLM 4.6",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      0.8,
				OutputPrice:     2.5,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"glm/glm-5-turbo": {
				ID:              "glm-5-turbo",
				Name:            "GLM 5 Turbo",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      1.4,
				OutputPrice:     4.4,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"glm/glm-5V-turbo": {
				ID:              "glm-5V-turbo",
				Name:            "GLM 5V Turbo",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      1.4,
				OutputPrice:     4.4,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"glm/glm-4.7-flash": {
				ID:              "glm-4.7-flash",
				Name:            "GLM 4.7 Flash",
				Provider:        "glm",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      0.5,
				OutputPrice:     1.5,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			// MiniMax models
			"minimax/MiniMax-M3": {
				ID:              "MiniMax-M3",
				Name:            "MiniMax M3",
				Provider:        "minimax",
				ContextWindow:   1000000,
				MaxOutputTokens: 16384,
				InputPrice:      0.3,
				OutputPrice:     1.2,
				Capabilities:    []string{"tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"minimax/MiniMax-M2.7": {
				ID:              "MiniMax-M2.7",
				Name:            "MiniMax M2.7",
				Provider:        "minimax",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      1.0,
				OutputPrice:     4.0,
				Capabilities:    []string{"tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"minimax/MiniMax-M2.7-highspeed": {
				ID:              "MiniMax-M2.7-highspeed",
				Name:            "MiniMax M2.7 HighSpeed",
				Provider:        "minimax",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.7,
				OutputPrice:     2.8,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"minimax/MiniMax-M2.5": {
				ID:              "MiniMax-M2.5",
				Name:            "MiniMax M2.5",
				Provider:        "minimax",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.8,
				OutputPrice:     3.2,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"minimax/MiniMax-M2.1": {
				ID:              "MiniMax-M2.1",
				Name:            "MiniMax M2.1",
				Provider:        "minimax",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.5,
				OutputPrice:     2.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"minimax/MiniMax-M2": {
				ID:              "MiniMax-M2",
				Name:            "MiniMax M2",
				Provider:        "minimax",
				ContextWindow:   128000,
				MaxOutputTokens: 8192,
				InputPrice:      0.3,
				OutputPrice:     1.2,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			// Qwen models (Alibaba Cloud)
			"qwen/qwen3.8-max": {
				ID:              "qwen3.8-max",
				Name:            "Qwen3.8 Max",
				Provider:        "qwen",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      2.0,
				OutputPrice:     6.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"qwen/qwen3.7-plus": {
				ID:              "qwen3.7-plus",
				Name:            "Qwen3.7 Plus",
				Provider:        "qwen",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      0.4,
				OutputPrice:     1.6,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"qwen/qwen3.7-max": {
				ID:              "qwen3.7-max",
				Name:            "Qwen3.7 Max",
				Provider:        "qwen",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      2.5,
				OutputPrice:     7.5,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"qwen/qwen3-coder-plus": {
				ID:              "qwen3-coder-plus",
				Name:            "Qwen3 Coder Plus",
				Provider:        "qwen",
				ContextWindow:   131072,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"qwen/qwen3-coder": {
				ID:              "qwen3-coder",
				Name:            "Qwen3 Coder",
				Provider:        "qwen",
				ContextWindow:   131072,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"qwen/qwen-plus": {
				ID:              "qwen-plus",
				Name:            "Qwen Plus",
				Provider:        "qwen",
				ContextWindow:   131072,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"qwen/qwen-turbo": {
				ID:              "qwen-turbo",
				Name:            "Qwen Turbo",
				Provider:        "qwen",
				ContextWindow:   131072,
				MaxOutputTokens: 8192,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			// Anthropic models
			"anthropic/claude-sonnet-5": {
				ID:              "claude-sonnet-5",
				Name:            "Claude Sonnet 5",
				Provider:        "anthropic",
				ContextWindow:   1000000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     10.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"anthropic/claude-opus-5": {
				ID:              "claude-opus-5",
				Name:            "Claude Opus 5",
				Provider:        "anthropic",
				ContextWindow:   1000000,
				MaxOutputTokens: 128000,
				InputPrice:      5.0,
				OutputPrice:     25.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"anthropic/claude-haiku-4-5": {
				ID:              "claude-haiku-4-5",
				Name:            "Claude Haiku 4.5",
				Provider:        "anthropic",
				ContextWindow:   200000,
				MaxOutputTokens: 64000,
				InputPrice:      1.0,
				OutputPrice:     5.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"anthropic/claude-fable-5": {
				ID:              "claude-fable-5",
				Name:            "Claude Fable 5",
				Provider:        "anthropic",
				ContextWindow:   1000000,
				MaxOutputTokens: 128000,
				InputPrice:      10.0,
				OutputPrice:     50.0,
				Capabilities:    []string{"vision", "tools", "streaming", "thinking"},
				IsActive:        true,
			},
			"anthropic/claude-sonnet": {
				ID:              "claude-sonnet",
				Name:            "Claude Sonnet",
				Provider:        "anthropic",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      3.0,
				OutputPrice:     15.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"anthropic/claude-opus": {
				ID:              "claude-opus",
				Name:            "Claude Opus",
				Provider:        "anthropic",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      15.0,
				OutputPrice:     75.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"anthropic/claude-haiku": {
				ID:              "claude-haiku",
				Name:            "Claude Haiku",
				Provider:        "anthropic",
				ContextWindow:   200000,
				MaxOutputTokens: 8192,
				InputPrice:      0.8,
				OutputPrice:     4.0,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			// Gemini models
			"gemini/gemini-3.7-flash": {
				ID:              "gemini-3.7-flash",
				Name:            "Gemini 3.7 Flash",
				Provider:        "gemini",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"gemini/gemini-3.6-flash": {
				ID:              "gemini-3.6-flash",
				Name:            "Gemini 3.6 Flash",
				Provider:        "gemini",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"gemini/gemini-3.5-flash": {
				ID:              "gemini-3.5-flash",
				Name:            "Gemini 3.5 Flash",
				Provider:        "gemini",
				ContextWindow:   1000000,
				MaxOutputTokens: 65536,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			"gemini/gemini-2.5-flash": {
				ID:              "gemini-2.5-flash",
				Name:            "Gemini 2.5 Flash",
				Provider:        "gemini",
				ContextWindow:   1000000,
				MaxOutputTokens: 8192,
				InputPrice:      0.15,
				OutputPrice:     0.6,
				Capabilities:    []string{"vision", "tools", "streaming"},
				IsActive:        true,
			},
			// Grok Build (xAI) models
			"xai/grok-4.6": {
				ID:              "grok-4.6",
				Name:            "Grok 4.6",
				Provider:        "xai",
				ContextWindow:   500000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     6.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-4.5": {
				ID:              "grok-4.5",
				Name:            "Grok 4.5",
				Provider:        "xai",
				ContextWindow:   500000,
				MaxOutputTokens: 128000,
				InputPrice:      2.0,
				OutputPrice:     6.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-build-0.1": {
				ID:              "grok-build-0.1",
				Name:            "Grok Build 0.1",
				Provider:        "xai",
				ContextWindow:   256000,
				MaxOutputTokens: 32768,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-4.3": {
				ID:              "grok-4.3",
				Name:            "Grok 4.3",
				Provider:        "xai",
				ContextWindow:   256000,
				MaxOutputTokens: 32768,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-4.20-0309-reasoning": {
				ID:              "grok-4.20-0309-reasoning",
				Name:            "Grok 4.20 Reasoning",
				Provider:        "xai",
				ContextWindow:   256000,
				MaxOutputTokens: 32768,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-4.20-0309-non-reasoning": {
				ID:              "grok-4.20-0309-non-reasoning",
				Name:            "Grok 4.20 Non-Reasoning",
				Provider:        "xai",
				ContextWindow:   256000,
				MaxOutputTokens: 32768,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"xai/grok-4.20-multi-agent-0309": {
				ID:              "grok-4.20-multi-agent-0309",
				Name:            "Grok 4.20 Multi-Agent",
				Provider:        "xai",
				ContextWindow:   256000,
				MaxOutputTokens: 32768,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-3-mini": {
				ID:              "grok-3-mini",
				Name:            "Grok 3 Mini",
				Provider:        "xai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			"xai/grok-3-mini-fast": {
				ID:              "grok-3-mini-fast",
				Name:            "Grok 3 Mini Fast",
				Provider:        "xai",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming", "reasoning"},
				IsActive:        true,
			},
			// Image generation models
			"openai/dall-e-3": {
				ID:              "dall-e-3",
				Name:            "DALL·E 3",
				Provider:        "openai",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
			},
			"openai/gpt-image-2": {
				ID:              "gpt-image-2",
				Name:            "GPT Image 2",
				Provider:        "openai",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
			},
			"openai/gpt-image-1.5": {
				ID:              "gpt-image-1.5",
				Name:            "GPT Image 1.5",
				Provider:        "openai",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
			},
			"xai/grok-imagine-image": {
				ID:              "grok-imagine-image",
				Name:            "Grok Imagine Image",
				Provider:        "xai",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
			},
			"xai/grok-imagine-image-quality": {
				ID:              "grok-imagine-image-quality",
				Name:            "Grok Imagine Image Quality",
				Provider:        "xai",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
			},
			"minimax/image-01": {
				ID:              "image-01",
				Name:            "MiniMax Image 01",
				Provider:        "minimax",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation"},
				IsActive:        true,
				Metadata: map[string]interface{}{
					"pricePerImage":  0.0035,
					"maxImages":      9,
					"maxPromptChars": 1500,
				},
			},
			"byteplus/dola-seedream-5-0-pro-260628": {
				ID:              "dola-seedream-5-0-pro-260628",
				Name:            "BytePlus Seedream 5.0 Pro",
				Provider:        "byteplus",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
				Metadata: map[string]interface{}{
					"pricePerImage": 0.045,
					"maxReferences": 10,
				},
			},
			"byteplus/seedream-5-0-lite-260128": {
				ID:              "seedream-5-0-lite-260128",
				Name:            "BytePlus Seedream 5.0 Lite",
				Provider:        "byteplus",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
				Metadata: map[string]interface{}{
					"pricePerImage": 0.035,
					"maxReferences": 14,
				},
			},
			"byteplus/seedream-4-5-251128": {
				ID:              "seedream-4-5-251128",
				Name:            "BytePlus Seedream 4.5",
				Provider:        "byteplus",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
				Metadata: map[string]interface{}{
					"pricePerImage": 0.04,
					"maxReferences": 14,
				},
			},
			"gemini/gemini-3.1-flash-image": {
				ID:              "gemini-3.1-flash-image",
				Name:            "Gemini 3.1 Flash Image",
				Provider:        "gemini",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
			},
			"gemini/gemini-3.1-flash-lite-image": {
				ID:              "gemini-3.1-flash-lite-image",
				Name:            "Gemini 3.1 Flash Lite Image",
				Provider:        "gemini",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
			},
			"gemini/gemini-3-pro-image": {
				ID:              "gemini-3-pro-image",
				Name:            "Gemini 3 Pro Image",
				Provider:        "gemini",
				ContextWindow:   1,
				MaxOutputTokens: 1,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"image-generation", "image-edit"},
				IsActive:        true,
			},
			// ClinePass models (subscription, price=0)
			"cline/cline-pass/kimi-k3": {
				ID:              "cline-pass/kimi-k3",
				Name:            "ClinePass Kimi K3",
				Provider:        "cline",
				ContextWindow:   1000000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/qwen3.8-max": {
				ID:              "cline-pass/qwen3.8-max",
				Name:            "ClinePass Qwen3.8 Max",
				Provider:        "cline",
				ContextWindow:   1000000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/glm-5.2": {
				ID:              "cline-pass/glm-5.2",
				Name:            "ClinePass GLM 5.2",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/kimi-k2.7-code": {
				ID:              "cline-pass/kimi-k2.7-code",
				Name:            "ClinePass Kimi K2.7 Code",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/kimi-k2.6": {
				ID:              "cline-pass/kimi-k2.6",
				Name:            "ClinePass Kimi K2.6",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/deepseek-v4-pro": {
				ID:              "cline-pass/deepseek-v4-pro",
				Name:            "ClinePass DeepSeek V4 Pro",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/deepseek-v4-flash": {
				ID:              "cline-pass/deepseek-v4-flash",
				Name:            "ClinePass DeepSeek V4 Flash",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/mimo-v2.5": {
				ID:              "cline-pass/mimo-v2.5",
				Name:            "ClinePass MiMo V2.5",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/mimo-v2.5-pro": {
				ID:              "cline-pass/mimo-v2.5-pro",
				Name:            "ClinePass MiMo V2.5 Pro",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/minimax-m3": {
				ID:              "cline-pass/minimax-m3",
				Name:            "ClinePass MiniMax M3",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/qwen3.7-max": {
				ID:              "cline-pass/qwen3.7-max",
				Name:            "ClinePass Qwen3.7 Max",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"cline/cline-pass/qwen3.7-plus": {
				ID:              "cline-pass/qwen3.7-plus",
				Name:            "ClinePass Qwen3.7 Plus",
				Provider:        "cline",
				ContextWindow:   128000,
				MaxOutputTokens: 16384,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/deepseek/deepseek-v4-pro": {
				ID:              "deepseek/deepseek-v4-pro",
				Name:            "DeepSeek V4 Pro",
				Provider:        "commandcode",
				ContextWindow:   1000000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/deepseek/deepseek-v4-flash": {
				ID:              "deepseek/deepseek-v4-flash",
				Name:            "DeepSeek V4 Flash",
				Provider:        "commandcode",
				ContextWindow:   1000000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/MiniMaxAI/MiniMax-M3": {
				ID:              "MiniMaxAI/MiniMax-M3",
				Name:            "MiniMax M3",
				Provider:        "commandcode",
				ContextWindow:   200000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/MiniMaxAI/MiniMax-M2.7": {
				ID:              "MiniMaxAI/MiniMax-M2.7",
				Name:            "MiniMax M2.7",
				Provider:        "commandcode",
				ContextWindow:   200000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/zai-org/GLM-5.1": {
				ID:              "zai-org/GLM-5.1",
				Name:            "GLM-5.1",
				Provider:        "commandcode",
				ContextWindow:   200000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/moonshotai/Kimi-K2.6": {
				ID:              "moonshotai/Kimi-K2.6",
				Name:            "Kimi K2.6",
				Provider:        "commandcode",
				ContextWindow:   256000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/Qwen/Qwen3.7-Max": {
				ID:              "Qwen/Qwen3.7-Max",
				Name:            "Qwen 3.7 Max",
				Provider:        "commandcode",
				ContextWindow:   256000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/Qwen/Qwen3.7-Max-Free": {
				ID:              "Qwen/Qwen3.7-Max-Free",
				Name:            "Qwen 3.7 Max Free",
				Provider:        "commandcode",
				ContextWindow:   256000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/stepfun/Step-3.7-Flash": {
				ID:              "stepfun/Step-3.7-Flash",
				Name:            "Step 3.7 Flash",
				Provider:        "commandcode",
				ContextWindow:   256000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
			"commandcode/xiaomi/mimo-v2.5-pro": {
				ID:              "xiaomi/mimo-v2.5-pro",
				Name:            "MiMo V2.5 Pro",
				Provider:        "commandcode",
				ContextWindow:   256000,
				MaxOutputTokens: 64000,
				InputPrice:      0.0,
				OutputPrice:     0.0,
				Capabilities:    []string{"tools", "streaming"},
				IsActive:        true,
			},
		},
	}
}

// GetModel returns a model definition by full key (provider/model-id).
func (r *ModelRegistry) GetModel(key string) *ModelDefinition {
	if r.Models == nil {
		return nil
	}
	return r.Models[key]
}

// Deprecated: Use GetProviderConfig("kiro").DefaultModels instead.
func DefaultKiroModels() []string {
	return GetProviderConfig("kiro").DefaultModels
}

// Deprecated: Use GetProviderConfig("glm").DefaultModels instead.
func DefaultGLMModels() []string {
	return GetProviderConfig("glm").DefaultModels
}

// Deprecated: Use GetProviderConfig("minimax").DefaultModels instead.
func DefaultMiniMaxModels() []string {
	return GetProviderConfig("minimax").DefaultModels
}

// Deprecated: Use GetProviderConfig("qwen").DefaultModels instead.
func DefaultQwenModels() []string {
	return GetProviderConfig("qwen").DefaultModels
}

// GetModelsByProvider returns all models for a given provider.
func (r *ModelRegistry) GetModelsByProvider(provider string) []*ModelDefinition {
	var result []*ModelDefinition
	for _, model := range r.Models {
		if model.Provider == provider && model.IsActive {
			result = append(result, model)
		}
	}
	return result
}

// AddOrUpdateModel adds or updates a model definition.
func (r *ModelRegistry) AddOrUpdateModel(key string, model *ModelDefinition) {
	if r.Models == nil {
		r.Models = make(map[string]*ModelDefinition)
	}
	r.Models[key] = model
}

// RemoveModel removes a model definition.
func (r *ModelRegistry) RemoveModel(key string) {
	if r.Models != nil {
		delete(r.Models, key)
	}
}

// GetRecommendedModelsForProvider returns the curated recommended model list for a provider.
// ProviderConfigs[providerID].RecommendedModels is the single source of truth for registered
// providers. This function exists for callers that don't have access to the config map directly,
// and as a fallback registry scan for unknown/dynamic providers.
func GetRecommendedModelsForProvider(providerID string) []string {
	// For all registered providers, delegate to ProviderConfigs — single source of truth.
	if cfg, ok := ProviderConfigs[providerID]; ok && len(cfg.RecommendedModels) > 0 {
		return cfg.RecommendedModels
	}
	// Fallback for unknown/dynamic providers: scan registry for active models.
	registry := DefaultModelRegistry()
	var models []string
	for key, m := range registry.Models {
		if m.Provider == providerID && m.IsActive {
			parts := strings.Split(key, "/")
			if len(parts) >= 2 {
				models = append(models, strings.Join(parts[1:], "/"))
			}
		}
	}
	sort.Strings(models)
	return models
}

// GetModelContextWindow returns the context window size for a model.
// Falls back to provider-level defaults when the model is not in the registry.
func GetModelContextWindow(model, provider string) int {
	registry := DefaultModelRegistry()
	key := provider + "/" + model
	if def := registry.GetModel(key); def != nil {
		return def.ContextWindow
	}
	// Provider-level fallbacks
	switch provider {
	case "kiro":
		return 200000
	case "openai":
		return 128000
	case "anthropic":
		return 200000
	case "commandcode":
		return 256000
	default:
		return 128000
	}
}

// GetDefaultModelsForProvider is kept for backward compatibility.
func GetDefaultModelsForProvider(providerID string) []string {
	return GetRecommendedModelsForProvider(providerID)
}
